/**
 * Quick-add staples for meal logging (approximate USDA / label averages).
 * @typedef {{ id: string, emoji: string, label: string, food_name: string, calories: number, protein_g: number, carbs_g: number, fats_g: number, portion_grams?: number|null, portion_ml?: number|null, meal_type?: string }} CommonFoodItem
 */

/** @type {{ id: string, label: string, items: CommonFoodItem[] }[]} */
export const COMMON_FOOD_TABS = [
  {
    id: 'protein',
    label: 'Protein',
    items: [
      { id: 'chicken_breast_100', emoji: '🍗', label: 'Chicken Breast (100g)', food_name: 'Chicken breast', calories: 165, protein_g: 31, carbs_g: 0, fats_g: 3.6, portion_grams: 100 },
      { id: 'turkey_breast_100', emoji: '🦃', label: 'Turkey Breast (100g)', food_name: 'Turkey breast', calories: 135, protein_g: 30, carbs_g: 0, fats_g: 1, portion_grams: 100 },
      { id: 'tuna_can_100', emoji: '🐟', label: 'Tuna canned (100g)', food_name: 'Tuna canned', calories: 116, protein_g: 26, carbs_g: 0, fats_g: 1, portion_grams: 100 },
      { id: 'salmon_100', emoji: '🐠', label: 'Salmon (100g)', food_name: 'Salmon', calories: 208, protein_g: 20, carbs_g: 0, fats_g: 13, portion_grams: 100 },
      { id: 'cod_100', emoji: '🐟', label: 'Cod (100g)', food_name: 'Cod', calories: 82, protein_g: 18, carbs_g: 0, fats_g: 0.7, portion_grams: 100 },
      { id: 'egg_large', emoji: '🥚', label: 'Egg (1 large)', food_name: 'Egg', calories: 78, protein_g: 6, carbs_g: 0.6, fats_g: 5.3, portion_grams: 50 },
      { id: 'egg_white_large', emoji: '🥚', label: 'Egg white (1 large)', food_name: 'Egg white', calories: 17, protein_g: 3.6, carbs_g: 0.2, fats_g: 0, portion_grams: 33 },
      { id: 'greek_yogurt_170', emoji: '🥛', label: 'Greek yogurt (170g)', food_name: 'Greek yogurt', calories: 100, protein_g: 17, carbs_g: 6, fats_g: 0.7, portion_grams: 170 },
      { id: 'cottage_cheese_100', emoji: '🧀', label: 'Cottage cheese (100g)', food_name: 'Cottage cheese', calories: 98, protein_g: 11, carbs_g: 3.4, fats_g: 4.3, portion_grams: 100 },
      { id: 'beef_mince_5_100', emoji: '🥩', label: 'Beef mince 5% (100g)', food_name: 'Beef mince 5%', calories: 137, protein_g: 21, carbs_g: 0, fats_g: 5.5, portion_grams: 100 },
      { id: 'sirloin_100', emoji: '🥩', label: 'Sirloin steak (100g)', food_name: 'Sirloin steak', calories: 207, protein_g: 26, carbs_g: 0, fats_g: 11, portion_grams: 100 },
      { id: 'prawns_100', emoji: '🦐', label: 'Prawns (100g)', food_name: 'Prawns', calories: 85, protein_g: 20, carbs_g: 0.9, fats_g: 0.5, portion_grams: 100 },
      { id: 'protein_shake_30', emoji: '🥤', label: 'Protein shake (30g)', food_name: 'Protein shake', calories: 120, protein_g: 24, carbs_g: 3, fats_g: 2, portion_grams: 30 },
      { id: 'quark_100', emoji: '🥣', label: 'Quark (100g)', food_name: 'Quark', calories: 67, protein_g: 12, carbs_g: 4, fats_g: 0.2, portion_grams: 100 },
      { id: 'tofu_100', emoji: '🧊', label: 'Tofu (100g)', food_name: 'Tofu', calories: 76, protein_g: 8, carbs_g: 1.9, fats_g: 4.8, portion_grams: 100 },
      { id: 'tempeh_100', emoji: '🫘', label: 'Tempeh (100g)', food_name: 'Tempeh', calories: 193, protein_g: 19, carbs_g: 9, fats_g: 11, portion_grams: 100 },
      { id: 'lentils_cooked_100', emoji: '🫘', label: 'Lentils cooked (100g)', food_name: 'Lentils cooked', calories: 116, protein_g: 9, carbs_g: 20, fats_g: 0.4, portion_grams: 100 },
      { id: 'chickpeas_cooked_100', emoji: '🫘', label: 'Chickpeas cooked (100g)', food_name: 'Chickpeas cooked', calories: 164, protein_g: 8.9, carbs_g: 27, fats_g: 2.6, portion_grams: 100 },
      { id: 'black_beans_cooked_100', emoji: '🫘', label: 'Black beans (100g)', food_name: 'Black beans cooked', calories: 132, protein_g: 8.9, carbs_g: 24, fats_g: 0.5, portion_grams: 100 },
      { id: 'edamame_100', emoji: '🫛', label: 'Edamame (100g)', food_name: 'Edamame', calories: 121, protein_g: 11, carbs_g: 10, fats_g: 5.2, portion_grams: 100 },
      { id: 'whey_bar', emoji: '🍫', label: 'Protein bar', food_name: 'Protein bar', calories: 200, protein_g: 20, carbs_g: 22, fats_g: 6, portion_grams: 60 },
      { id: 'ham_lean_100', emoji: '🥓', label: 'Ham lean (100g)', food_name: 'Ham lean', calories: 145, protein_g: 21, carbs_g: 1.5, fats_g: 6, portion_grams: 100 },
      { id: 'pork_tenderloin_100', emoji: '🥩', label: 'Pork tenderloin (100g)', food_name: 'Pork tenderloin', calories: 143, protein_g: 26, carbs_g: 0, fats_g: 3.5, portion_grams: 100 },
      { id: 'duck_breast_100', emoji: '🦆', label: 'Duck breast (100g)', food_name: 'Duck breast', calories: 201, protein_g: 19, carbs_g: 0, fats_g: 13, portion_grams: 100 },
      { id: 'lamb_leg_100', emoji: '🐑', label: 'Lamb leg (100g)', food_name: 'Lamb leg', calories: 206, protein_g: 25, carbs_g: 0, fats_g: 11, portion_grams: 100 },
      { id: 'venison_100', emoji: '🦌', label: 'Venison (100g)', food_name: 'Venison', calories: 158, protein_g: 30, carbs_g: 0, fats_g: 3.2, portion_grams: 100 },
      { id: 'bison_100', emoji: '🦬', label: 'Bison (100g)', food_name: 'Bison', calories: 109, protein_g: 20, carbs_g: 0, fats_g: 2.4, portion_grams: 100 },
      { id: 'tilapia_100', emoji: '🐟', label: 'Tilapia (100g)', food_name: 'Tilapia', calories: 96, protein_g: 20, carbs_g: 0, fats_g: 1.7, portion_grams: 100 },
      { id: 'mackerel_100', emoji: '🐟', label: 'Mackerel (100g)', food_name: 'Mackerel', calories: 205, protein_g: 19, carbs_g: 0, fats_g: 14, portion_grams: 100 },
      { id: 'sardines_can', emoji: '🥫', label: 'Sardines canned', food_name: 'Sardines canned', calories: 208, protein_g: 25, carbs_g: 0, fats_g: 11, portion_grams: 90 },
      { id: 'skyr_150', emoji: '🥛', label: 'Skyr (150g)', food_name: 'Skyr', calories: 100, protein_g: 17, carbs_g: 6, fats_g: 0.2, portion_grams: 150 },
      { id: 'mozzarella_30', emoji: '🧀', label: 'Mozzarella (30g)', food_name: 'Mozzarella', calories: 85, protein_g: 6.3, carbs_g: 0.6, fats_g: 6.3, portion_grams: 30 },
      { id: 'feta_30', emoji: '🧀', label: 'Feta (30g)', food_name: 'Feta cheese', calories: 80, protein_g: 4.3, carbs_g: 1, fats_g: 6.4, portion_grams: 30 },
      { id: 'halloumi_40', emoji: '🧀', label: 'Halloumi (40g)', food_name: 'Halloumi', calories: 129, protein_g: 9.2, carbs_g: 0.7, fats_g: 10, portion_grams: 40 },
      { id: 'protein_pancakes', emoji: '🥞', label: 'Protein pancakes', food_name: 'Protein pancakes', calories: 320, protein_g: 28, carbs_g: 35, fats_g: 8, portion_grams: 180 },
      { id: 'beef_jerky_40', emoji: '🥩', label: 'Beef jerky (40g)', food_name: 'Beef jerky', calories: 116, protein_g: 14, carbs_g: 3, fats_g: 3.5, portion_grams: 40 },
      { id: 'creatine_5', emoji: '⚡', label: 'Creatine (5g)', food_name: 'Creatine', calories: 0, protein_g: 0, carbs_g: 0, fats_g: 0, portion_grams: 5 },
      { id: 'bcaa_10', emoji: '⚡', label: 'BCAA (10g)', food_name: 'BCAA powder', calories: 40, protein_g: 8, carbs_g: 0, fats_g: 0, portion_grams: 10 },
      { id: 'preworkout', emoji: '⚡', label: 'Pre-workout (1 scoop)', food_name: 'Pre-workout', calories: 15, protein_g: 0, carbs_g: 3, fats_g: 0, portion_grams: 8 },
    ],
  },
  {
    id: 'carbs',
    label: 'Carbs',
    items: [
      { id: 'white_rice_100', emoji: '🍚', label: 'White rice cooked (100g)', food_name: 'White rice cooked', calories: 130, protein_g: 2.7, carbs_g: 28, fats_g: 0.3, portion_grams: 100 },
      { id: 'brown_rice_100', emoji: '🍚', label: 'Brown rice cooked (100g)', food_name: 'Brown rice cooked', calories: 112, protein_g: 2.3, carbs_g: 23, fats_g: 0.8, portion_grams: 100 },
      { id: 'sweet_potato_100', emoji: '🍠', label: 'Sweet potato (100g)', food_name: 'Sweet potato', calories: 86, protein_g: 1.6, carbs_g: 20, fats_g: 0.1, portion_grams: 100 },
      { id: 'white_potato_100', emoji: '🥔', label: 'White potato (100g)', food_name: 'White potato', calories: 77, protein_g: 2, carbs_g: 17, fats_g: 0.1, portion_grams: 100 },
      { id: 'oats_dry_100', emoji: '🥣', label: 'Oats dry (100g)', food_name: 'Oats dry', calories: 389, protein_g: 17, carbs_g: 66, fats_g: 7, portion_grams: 100 },
      { id: 'pasta_cooked_100', emoji: '🍝', label: 'Pasta cooked (100g)', food_name: 'Pasta cooked', calories: 131, protein_g: 5, carbs_g: 25, fats_g: 1, portion_grams: 100 },
      { id: 'bread_slice_40', emoji: '🍞', label: 'Bread (1 slice ~40g)', food_name: 'Bread slice', calories: 106, protein_g: 3.6, carbs_g: 20, fats_g: 1.3, portion_grams: 40 },
      { id: 'banana_med', emoji: '🍌', label: 'Banana (medium)', food_name: 'Banana', calories: 89, protein_g: 1.1, carbs_g: 23, fats_g: 0.3, portion_grams: 118 },
      { id: 'apple_med', emoji: '🍎', label: 'Apple (medium)', food_name: 'Apple', calories: 52, protein_g: 0.3, carbs_g: 14, fats_g: 0.2, portion_grams: 150 },
      { id: 'orange_med', emoji: '🍊', label: 'Orange (medium)', food_name: 'Orange', calories: 62, protein_g: 1.2, carbs_g: 15, fats_g: 0.2, portion_grams: 130 },
      { id: 'blueberries_100', emoji: '🫐', label: 'Blueberries (100g)', food_name: 'Blueberries', calories: 57, protein_g: 0.7, carbs_g: 14, fats_g: 0.3, portion_grams: 100 },
      { id: 'mango_100', emoji: '🥭', label: 'Mango (100g)', food_name: 'Mango', calories: 60, protein_g: 0.8, carbs_g: 15, fats_g: 0.4, portion_grams: 100 },
      { id: 'dates_30', emoji: '🌴', label: 'Dates (30g)', food_name: 'Dates', calories: 84, protein_g: 0.6, carbs_g: 23, fats_g: 0.1, portion_grams: 30 },
      { id: 'granola_50', emoji: '🥣', label: 'Granola (50g)', food_name: 'Granola', calories: 224, protein_g: 4.5, carbs_g: 30, fats_g: 9.3, portion_grams: 50 },
      { id: 'bagel_one', emoji: '🥯', label: 'Bagel (1)', food_name: 'Bagel', calories: 245, protein_g: 9, carbs_g: 48, fats_g: 1.5, portion_grams: 95 },
      { id: 'couscous_cooked_100', emoji: '🍚', label: 'Couscous cooked (100g)', food_name: 'Couscous cooked', calories: 112, protein_g: 3.8, carbs_g: 23, fats_g: 0.2, portion_grams: 100 },
      { id: 'quinoa_cooked_100', emoji: '🍚', label: 'Quinoa cooked (100g)', food_name: 'Quinoa cooked', calories: 120, protein_g: 4.4, carbs_g: 21, fats_g: 1.9, portion_grams: 100 },
      { id: 'tortilla_wrap', emoji: '🌯', label: 'Flour tortilla (1)', food_name: 'Flour tortilla', calories: 140, protein_g: 4, carbs_g: 22, fats_g: 3.5, portion_grams: 45 },
      { id: 'rice_cakes_3', emoji: '🍘', label: 'Rice cakes (3)', food_name: 'Rice cakes', calories: 105, protein_g: 2.1, carbs_g: 23, fats_g: 0.6, portion_grams: 27 },
      { id: 'honey_15', emoji: '🍯', label: 'Honey (15g)', food_name: 'Honey', calories: 46, protein_g: 0, carbs_g: 12.5, fats_g: 0, portion_grams: 15 },
      { id: 'maple_15', emoji: '🍁', label: 'Maple syrup (15g)', food_name: 'Maple syrup', calories: 52, protein_g: 0, carbs_g: 13.4, fats_g: 0, portion_grams: 15 },
      { id: 'jam_15', emoji: '🫙', label: 'Jam (15g)', food_name: 'Jam', calories: 39, protein_g: 0.1, carbs_g: 10, fats_g: 0, portion_grams: 15 },
      { id: 'corn_100', emoji: '🌽', label: 'Sweet corn (100g)', food_name: 'Sweet corn', calories: 86, protein_g: 3.3, carbs_g: 19, fats_g: 1.4, portion_grams: 100 },
      { id: 'peas_100', emoji: '🫛', label: 'Peas (100g)', food_name: 'Peas', calories: 81, protein_g: 5.4, carbs_g: 14, fats_g: 0.4, portion_grams: 100 },
      { id: 'butternut_100', emoji: '🎃', label: 'Butternut squash (100g)', food_name: 'Butternut squash', calories: 45, protein_g: 1, carbs_g: 12, fats_g: 0.1, portion_grams: 100 },
      { id: 'beetroot_100', emoji: '🔴', label: 'Beetroot (100g)', food_name: 'Beetroot', calories: 43, protein_g: 1.6, carbs_g: 10, fats_g: 0.2, portion_grams: 100 },
      { id: 'watermelon_200', emoji: '🍉', label: 'Watermelon (200g)', food_name: 'Watermelon', calories: 60, protein_g: 1.2, carbs_g: 15, fats_g: 0.3, portion_grams: 200 },
      { id: 'grapes_150', emoji: '🍇', label: 'Grapes (150g)', food_name: 'Grapes', calories: 104, protein_g: 1.1, carbs_g: 27, fats_g: 0.3, portion_grams: 150 },
      { id: 'pear_med', emoji: '🍐', label: 'Pear (medium)', food_name: 'Pear', calories: 101, protein_g: 0.6, carbs_g: 27, fats_g: 0.2, portion_grams: 178 },
      { id: 'pineapple_100', emoji: '🍍', label: 'Pineapple (100g)', food_name: 'Pineapple', calories: 50, protein_g: 0.5, carbs_g: 13, fats_g: 0.1, portion_grams: 100 },
      { id: 'fruit_smoothie', emoji: '🥤', label: 'Fruit smoothie', food_name: 'Fruit smoothie', calories: 220, protein_g: 4, carbs_g: 45, fats_g: 2, portion_grams: 350 },
      { id: 'energy_gel', emoji: '⚡', label: 'Energy gel', food_name: 'Energy gel', calories: 90, protein_g: 0, carbs_g: 22, fats_g: 0, portion_grams: 32 },
      { id: 'sports_drink_500', emoji: '🥤', label: 'Sports drink (500ml)', food_name: 'Sports drink', calories: 120, protein_g: 0, carbs_g: 30, fats_g: 0, portion_ml: 500 },
    ],
  },
  {
    id: 'fats',
    label: 'Fats',
    items: [
      { id: 'avocado_half', emoji: '🥑', label: 'Avocado (half)', food_name: 'Avocado', calories: 160, protein_g: 2, carbs_g: 9, fats_g: 15, portion_grams: 68 },
      { id: 'almonds_30', emoji: '🌰', label: 'Almonds (30g)', food_name: 'Almonds', calories: 173, protein_g: 6, carbs_g: 6, fats_g: 15, portion_grams: 30 },
      { id: 'pb_30', emoji: '🥜', label: 'Peanut butter (30g)', food_name: 'Peanut butter', calories: 188, protein_g: 8, carbs_g: 6, fats_g: 16, portion_grams: 30 },
      { id: 'olive_oil_1tbsp', emoji: '🫒', label: 'Olive oil (1 tbsp)', food_name: 'Olive oil', calories: 119, protein_g: 0, carbs_g: 0, fats_g: 14, portion_grams: 14 },
      { id: 'milk_whole_200', emoji: '🥛', label: 'Whole milk (200ml)', food_name: 'Whole milk', calories: 122, protein_g: 6.4, carbs_g: 9.4, fats_g: 6.6, portion_ml: 200 },
      { id: 'cheddar_30', emoji: '🧀', label: 'Cheddar (30g)', food_name: 'Cheddar cheese', calories: 120, protein_g: 7.4, carbs_g: 0.1, fats_g: 10, portion_grams: 30 },
      { id: 'walnuts_30', emoji: '🌰', label: 'Walnuts (30g)', food_name: 'Walnuts', calories: 196, protein_g: 4.6, carbs_g: 4, fats_g: 19.6, portion_grams: 30 },
      { id: 'coconut_oil_1tbsp', emoji: '🥥', label: 'Coconut oil (1 tbsp)', food_name: 'Coconut oil', calories: 121, protein_g: 0, carbs_g: 0, fats_g: 14, portion_grams: 14 },
      { id: 'cashews_30', emoji: '🌰', label: 'Cashews (30g)', food_name: 'Cashews', calories: 163, protein_g: 4.3, carbs_g: 9.3, fats_g: 13, portion_grams: 30 },
      { id: 'dark_choc_30', emoji: '🍫', label: 'Dark chocolate 85% (30g)', food_name: 'Dark chocolate 85%', calories: 168, protein_g: 3, carbs_g: 8, fats_g: 14, portion_grams: 30 },
      { id: 'butter_10', emoji: '🧈', label: 'Butter (10g)', food_name: 'Butter', calories: 72, protein_g: 0.1, carbs_g: 0, fats_g: 8, portion_grams: 10 },
      { id: 'mayo_15', emoji: '🥄', label: 'Mayonnaise (15g)', food_name: 'Mayonnaise', calories: 100, protein_g: 0.1, carbs_g: 0.6, fats_g: 11, portion_grams: 15 },
      { id: 'hummus_50', emoji: '🫘', label: 'Hummus (50g)', food_name: 'Hummus', calories: 82, protein_g: 3.8, carbs_g: 8, fats_g: 4.5, portion_grams: 50 },
      { id: 'olives_30', emoji: '🫒', label: 'Olives (30g)', food_name: 'Olives', calories: 45, protein_g: 0.3, carbs_g: 1.2, fats_g: 4.2, portion_grams: 30 },
      { id: 'chia_20', emoji: '🫘', label: 'Chia seeds (20g)', food_name: 'Chia seeds', calories: 97, protein_g: 3.4, carbs_g: 8.4, fats_g: 6.1, portion_grams: 20 },
      { id: 'flax_15', emoji: '🫘', label: 'Ground flax (15g)', food_name: 'Ground flaxseed', calories: 75, protein_g: 2.6, carbs_g: 4, fats_g: 6, portion_grams: 15 },
      { id: 'pesto_30', emoji: '🌿', label: 'Pesto (30g)', food_name: 'Pesto', calories: 150, protein_g: 3.5, carbs_g: 2, fats_g: 15, portion_grams: 30 },
      { id: 'double_cream_30', emoji: '🥛', label: 'Double cream (30g)', food_name: 'Double cream', calories: 133, protein_g: 0.6, carbs_g: 0.8, fats_g: 14.5, portion_grams: 30 },
      { id: 'sour_cream_30', emoji: '🥛', label: 'Sour cream (30g)', food_name: 'Sour cream', calories: 64, protein_g: 0.9, carbs_g: 1.2, fats_g: 6.3, portion_grams: 30 },
      { id: 'nutella_15', emoji: '🍫', label: 'Chocolate spread (15g)', food_name: 'Chocolate hazelnut spread', calories: 82, protein_g: 0.9, carbs_g: 8.6, fats_g: 4.7, portion_grams: 15 },
      { id: 'macadamia_30', emoji: '🌰', label: 'Macadamia (30g)', food_name: 'Macadamia nuts', calories: 215, protein_g: 2.4, carbs_g: 4, fats_g: 23, portion_grams: 30 },
      { id: 'pecans_30', emoji: '🌰', label: 'Pecans (30g)', food_name: 'Pecans', calories: 206, protein_g: 2.7, carbs_g: 4.1, fats_g: 21.5, portion_grams: 30 },
      { id: 'pistachio_30', emoji: '🌰', label: 'Pistachios (30g)', food_name: 'Pistachios', calories: 164, protein_g: 6.2, carbs_g: 8.2, fats_g: 13.4, portion_grams: 30 },
      { id: 'sunflower_butter_30', emoji: '🌻', label: 'Sunflower butter (30g)', food_name: 'Sunflower seed butter', calories: 174, protein_g: 5.6, carbs_g: 6.4, fats_g: 15.7, portion_grams: 30 },
      { id: 'tahini_15', emoji: '🫘', label: 'Tahini (15g)', food_name: 'Tahini', calories: 89, protein_g: 2.6, carbs_g: 3.2, fats_g: 8, portion_grams: 15 },
    ],
  },
  {
    id: 'meals',
    label: 'Meals',
    items: [
      { id: 'scrambled_eggs_3', emoji: '🍳', label: 'Scrambled eggs x3 + butter', food_name: 'Scrambled eggs with butter', calories: 280, protein_g: 18, carbs_g: 1, fats_g: 22, portion_grams: 180, meal_type: 'breakfast' },
      { id: 'porridge_300', emoji: '🥣', label: 'Porridge oats + milk', food_name: 'Porridge oats and milk', calories: 280, protein_g: 10, carbs_g: 42, fats_g: 8, portion_grams: 300, meal_type: 'breakfast' },
      { id: 'chicken_rice_300', emoji: '🍛', label: 'Chicken + rice', food_name: 'Chicken and rice', calories: 370, protein_g: 40, carbs_g: 35, fats_g: 6, portion_grams: 300, meal_type: 'lunch' },
      { id: 'salmon_sweet_300', emoji: '🍽️', label: 'Salmon + sweet potato', food_name: 'Salmon and sweet potato', calories: 420, protein_g: 35, carbs_g: 30, fats_g: 12, portion_grams: 300, meal_type: 'dinner' },
      { id: 'protein_oats', emoji: '🥣', label: 'Protein oats', food_name: 'Protein oats', calories: 380, protein_g: 30, carbs_g: 45, fats_g: 8, portion_grams: 320, meal_type: 'breakfast' },
      { id: 'yogurt_berries', emoji: '🫐', label: 'Greek yogurt + berries', food_name: 'Greek yogurt and berries', calories: 180, protein_g: 18, carbs_g: 20, fats_g: 2, portion_grams: 220, meal_type: 'snack' },
      { id: 'egg_toast', emoji: '🍞', label: '2 eggs + 2 toast', food_name: 'Eggs on toast', calories: 340, protein_g: 18, carbs_g: 30, fats_g: 14, portion_grams: 220, meal_type: 'breakfast' },
      { id: 'beef_stirfry', emoji: '🥡', label: 'Beef stir fry + rice', food_name: 'Beef stir fry with rice', calories: 490, protein_g: 38, carbs_g: 48, fats_g: 12, portion_grams: 400, meal_type: 'dinner' },
      { id: 'turkey_sandwich', emoji: '🥪', label: 'Turkey sandwich', food_name: 'Turkey sandwich', calories: 380, protein_g: 28, carbs_g: 42, fats_g: 10, portion_grams: 300, meal_type: 'lunch' },
      { id: 'chicken_salad', emoji: '🥗', label: 'Chicken salad bowl', food_name: 'Chicken salad bowl', calories: 420, protein_g: 38, carbs_g: 18, fats_g: 22, portion_grams: 380, meal_type: 'lunch' },
      { id: 'tuna_pasta', emoji: '🍝', label: 'Tuna pasta', food_name: 'Tuna pasta', calories: 450, protein_g: 32, carbs_g: 55, fats_g: 10, portion_grams: 350, meal_type: 'dinner' },
      { id: 'full_english', emoji: '🍳', label: 'Full English (lighter)', food_name: 'Full English breakfast', calories: 520, protein_g: 28, carbs_g: 28, fats_g: 32, portion_grams: 380, meal_type: 'breakfast' },
      { id: 'sushi_roll', emoji: '🍣', label: 'Sushi rolls (8 pc)', food_name: 'Sushi rolls', calories: 320, protein_g: 12, carbs_g: 52, fats_g: 6, portion_grams: 220, meal_type: 'lunch' },
      { id: 'burrito', emoji: '🌯', label: 'Chicken burrito', food_name: 'Chicken burrito', calories: 650, protein_g: 35, carbs_g: 70, fats_g: 22, portion_grams: 350, meal_type: 'lunch' },
      { id: 'fish_chips', emoji: '🐟', label: 'Fish + chips (small)', food_name: 'Fish and chips', calories: 700, protein_g: 28, carbs_g: 75, fats_g: 32, portion_grams: 400, meal_type: 'dinner' },
      { id: 'pizza_slice_2', emoji: '🍕', label: 'Pizza (2 slices)', food_name: 'Pizza two slices', calories: 560, protein_g: 24, carbs_g: 64, fats_g: 22, portion_grams: 200, meal_type: 'dinner' },
      { id: 'burger_meal', emoji: '🍔', label: 'Burger meal', food_name: 'Burger and fries', calories: 900, protein_g: 35, carbs_g: 90, fats_g: 42, portion_grams: 450, meal_type: 'dinner' },
      { id: 'pho', emoji: '🍜', label: 'Chicken pho', food_name: 'Chicken pho', calories: 420, protein_g: 28, carbs_g: 55, fats_g: 8, portion_grams: 550, meal_type: 'lunch' },
      { id: 'ramen', emoji: '🍜', label: 'Ramen bowl', food_name: 'Ramen bowl', calories: 520, protein_g: 18, carbs_g: 65, fats_g: 18, portion_grams: 500, meal_type: 'dinner' },
      { id: 'poke', emoji: '🥣', label: 'Poke bowl', food_name: 'Poke bowl', calories: 550, protein_g: 32, carbs_g: 62, fats_g: 16, portion_grams: 450, meal_type: 'lunch' },
      { id: 'nando_grill', emoji: '🍗', label: 'Grilled chicken meal', food_name: 'Grilled chicken meal', calories: 580, protein_g: 48, carbs_g: 45, fats_g: 18, portion_grams: 400, meal_type: 'dinner' },
      { id: 'meal_prep_chicken', emoji: '🍱', label: 'Meal prep: chicken veg', food_name: 'Meal prep chicken vegetables', calories: 440, protein_g: 42, carbs_g: 35, fats_g: 12, portion_grams: 400, meal_type: 'lunch' },
    ],
  },
];

export const ALL_COMMON_FOODS = COMMON_FOOD_TABS.flatMap((t) => t.items);
