/**
 * PRODUCT DECISION (May 2026):
 * Personal users build programmes manually. Auto-generation
 * removed intentionally — the manual experience creates the
 * natural ceiling that makes coaching the obvious next step.
 * Do not re-enable without product review.
 * Only exception: macro TARGETS (not plans) are still calculated.
 *
 * Coach / other roles: auto-build in program builder remains available
 * where `personalAutoProgramContextAllowed` permits (not Personal role).
 */

/** @typedef {'basic'|'enhanced'|'free'} PersonalPlanTier */
/** @typedef {'build_muscle'|'lose_fat'|'prep'|'general'} PersonalGoalCopyBucket */

const GOAL_ALIASES = {
  build_muscle: ['build_muscle', 'muscle', 'bulk', 'gain', 'hypertrophy', 'strength'],
  lose_fat: ['lose_fat', 'fat_loss', 'cut', 'recomp', 'lean'],
  prep: ['prep', 'competition', 'contest', 'stage', 'pre_contest'],
};

/**
 * @param {string|null|undefined} raw
 * @returns {PersonalGoalCopyBucket}
 */
export function normalizePersonalGoalForCopy(raw) {
  const g = String(raw || '')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, '_');
  if (!g) return 'general';
  for (const bucket of Object.keys(GOAL_ALIASES)) {
    if (GOAL_ALIASES[bucket].some((a) => g === a || g.includes(a))) {
      if (bucket === 'build_muscle') return 'build_muscle';
      if (bucket === 'lose_fat') return 'lose_fat';
      if (bucket === 'prep') return 'prep';
    }
  }
  return 'general';
}

/** Personal: never auto-generate starter programmes (tier argument ignored). */
export function personalTierAllowsAutoGeneratedStarterProgram(_tier) {
  return false;
}

/** Personal: no “Atlas built your plan” style messaging (tier argument ignored). */
export function personalTierAllowsBuiltPlanMessaging(_tier) {
  return false;
}

/** Smart macro starter targets — not a generated plan; allowed for Personal. */
export function personalTierAllowsSmartMacroStarter(_tier) {
  return true;
}

/**
 * Defense-in-depth for autoProgramBuilder.generateStarterProgram when role=personal.
 * @param {{ role?: string, personalPlanTier?: string|null }} context
 */
export function personalAutoProgramContextAllowed(context = {}) {
  if (String(context.role || '').toLowerCase() === 'personal') {
    return false;
  }
  return true;
}
