/**
 * Product architecture: Personal Basic vs Enhanced (solo mode).
 * Aligns with PERSONAL_FEATURES in personalPlanAccess.js — keep both in sync.
 *
 * BASIC: manual-first tracking; no auto-generated coach-like starter plans or Enhanced-only nudges.
 * ENHANCED: guided solo mode — starter structure, targets, light adjustments; not a coach replacement.
 */

/** @typedef {'basic'|'enhanced'} PersonalPlanTier */
/** @typedef {'build_muscle'|'lose_fat'|'prep'|'general'} PersonalGoalCopyBucket */

const GOAL_ALIASES = {
  build_muscle: ['build_muscle', 'muscle', 'bulk', 'gain', 'hypertrophy', 'strength'],
  lose_fat: ['lose_fat', 'fat_loss', 'cut', 'recomp', 'lean'],
  prep: ['prep', 'competition', 'contest', 'stage', 'pre_contest'],
};

/**
 * @param {string|null|undefined} raw
 * @returns {PersonalGoalCopyBucket}
 */
export function normalizePersonalGoalForCopy(raw) {
  const g = String(raw || '')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, '_');
  if (!g) return 'general';
  for (const bucket of Object.keys(GOAL_ALIASES)) {
    if (GOAL_ALIASES[bucket].some((a) => g === a || g.includes(a))) {
      if (bucket === 'build_muscle') return 'build_muscle';
      if (bucket === 'lose_fat') return 'lose_fat';
      if (bucket === 'prep') return 'prep';
    }
  }
  return 'general';
}

/**
 * Auto-generated starter week / macro logic: Enhanced only.
 * @param {PersonalPlanTier|string|null|undefined} tier
 */
export function personalTierAllowsAutoGeneratedStarterProgram(tier) {
  return String(tier || 'basic').toLowerCase() === 'enhanced';
}

/**
 * “Atlas built your plan” / coach-like automation copy must not apply to Basic.
 */
export function personalTierAllowsBuiltPlanMessaging(tier) {
  return personalTierAllowsAutoGeneratedStarterProgram(tier);
}

/**
 * Smart macro starter suggestions from Enhanced engines — Basic uses manual targets only.
 */
export function personalTierAllowsSmartMacroStarter(tier) {
  return personalTierAllowsAutoGeneratedStarterProgram(tier);
}

/**
 * Defense-in-depth for autoProgramBuilder.generateStarterProgram when role=personal.
 * @param {{ role?: string, personalPlanTier?: string|null }} context
 * @returns {boolean}
 */
export function personalAutoProgramContextAllowed(context = {}) {
  if (String(context.role || '').toLowerCase() !== 'personal') return true;
  return personalTierAllowsAutoGeneratedStarterProgram(context.personalPlanTier);
}
